### ISSUE TITLE
Launch Checklist 🚀🚀🚀

### ISSUE THREAD

**Issue by twilson63** [permaweb/U#31]
## Goals

The launch of reBAR should be:
* Useful
* Complete
* Scalable

This checklist is the minimum criteria for a successful launch

reBAR MUST

- [x] pass all automated tests
- [x] have a visible project owner
- [ ] have on and off ramps reBAR <> AR
- [x] have single onboarding website for communication
- [ ] have plan and comms on how `Bundler Services` will propagate the reBAR tokens to their users
  > One note, is nested bundles, I think we should have messaging about nested bundles and rewards will only be provided 1 layer deep. Also copy about getting reBAR using `bundler` services how reBAR recommends it work.
  > Would be nice to have an announced date to set expectations for community
- [x] removed all decimal balances
- [x] remove all previous claimable records
- [x] address state bloat, remove claims array
- [x] #36
- [x] #37
- [ ] deploy contract to mainnet
- [ ] update all applications and services using bAR to use reBAR
  - permafacts
  - alex
  - now
  - stamps
  - after
  - fair?
  - img
  - pst
  - pages
  - bundlr
  - ar.io
  - community labs
